import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function Privacy() {
  return (
    <>
      <Head>
        <title>Privacy Policy - AI Photo Enhancement</title>
        <meta name="description" content="Privacy Policy for AI Photo Enhancement service" />
      </Head>
      <Header />
      <main className="flex flex-1 w-full flex-col items-center justify-center text-center px-4 mt-4 sm:mb-0 mb-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
          
          <div className="text-left space-y-6">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Information We Collect</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-medium mb-2">Personal Information</h3>
                  <ul className="text-gray-700 leading-relaxed list-disc pl-6 space-y-1">
                    <li>Email address (when you sign in with Google)</li>
                    <li>Profile information from your Google account</li>
                    <li>Usage data and service interactions</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-medium mb-2">Photo Data</h3>
                  <ul className="text-gray-700 leading-relaxed list-disc pl-6 space-y-1">
                    <li>Photos you upload for enhancement</li>
                    <li>Enhanced photos generated by our AI service</li>
                    <li>Processing metadata and usage statistics</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. How We Use Your Information</h2>
              <ul className="text-gray-700 leading-relaxed list-disc pl-6 space-y-2">
                <li>To provide and improve our AI photo enhancement service</li>
                <li>To process your photo uploads and generate enhanced images</li>
                <li>To track usage limits and prevent abuse</li>
                <li>To communicate with you about service updates or issues</li>
                <li>To analyze service performance and user behavior</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. Data Storage and Security</h2>
              <div className="space-y-4">
                <p className="text-gray-700 leading-relaxed">
                  We use secure cloud storage services to store your photos and data. All data is encrypted in transit and at rest. We implement industry-standard security measures to protect your information.
                </p>
                <div>
                  <h3 className="text-lg font-medium mb-2">Photo Storage</h3>
                  <ul className="text-gray-700 leading-relaxed list-disc pl-6 space-y-1">
                    <li>Photos are temporarily stored for processing</li>
                    <li>Enhanced photos are stored for a limited time for your access</li>
                    <li>We do not permanently store your original photos</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. Third-Party Services</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                We use the following third-party services to provide our functionality:
              </p>
              <ul className="text-gray-700 leading-relaxed list-disc pl-6 space-y-2">
                <li><strong>Google OAuth:</strong> For user authentication and sign-in</li>
                <li><strong>Replicate:</strong> For AI photo enhancement processing</li>
                <li><strong>Bytescale:</strong> For secure file upload and storage</li>
                <li><strong>Upstash Redis:</strong> For usage tracking and rate limiting</li>
                <li><strong>Vercel:</strong> For hosting and deployment</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Analytics and Tracking</h2>
              <p className="text-gray-700 leading-relaxed">
                We use Google Analytics and Microsoft Clarity to understand how users interact with our service. These services may collect information about your device, browser, and usage patterns. You can opt out of analytics tracking through your browser settings.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Data Retention</h2>
              <ul className="text-gray-700 leading-relaxed list-disc pl-6 space-y-2">
                <li>User account information is retained while your account is active</li>
                <li>Uploaded photos are automatically deleted after processing</li>
                <li>Enhanced photos are stored for a limited period for your access</li>
                <li>Usage data is retained for service optimization and abuse prevention</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">7. Your Rights</h2>
              <ul className="text-gray-700 leading-relaxed list-disc pl-6 space-y-2">
                <li>Access your personal data and usage information</li>
                <li>Request deletion of your account and associated data</li>
                <li>Opt out of analytics tracking</li>
                <li>Contact us with privacy concerns or questions</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">8. Children's Privacy</h2>
              <p className="text-gray-700 leading-relaxed">
                Our service is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">9. Changes to This Policy</h2>
              <p className="text-gray-700 leading-relaxed">
                We may update this Privacy Policy from time to time. We will notify users of any material changes by posting the new policy on this page and updating the "Last updated" date.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">10. Contact Us</h2>
              <p className="text-gray-700 leading-relaxed">
                If you have any questions about this Privacy Policy or our data practices, please contact us at wendy.1031ht@gmail.com.
              </p>
            </section>

            <section className="pt-6">
              <p className="text-sm text-gray-500">
                Last updated: {new Date().toLocaleDateString()}
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
} 